GLOBAL-1105/1106 Реализовано редактирование имени и аватара группового чата
fasthome/Android-Fenestram-Messenger pull request #127
Opened 2022-09-27 15:18 UTC by RudakoVladimir

2022-09-29 12:54 UTC, jizis138 requested changes

2022-09-29 12:54 UTC, jizis138 commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/data/service/MessengerService.kt
> +        client.runPatch<PatchChatAvatarRequest, BaseResponse<PatchChatAvatarRequest>>(
для тела и ответа запроса должны быть разные модели, модели ответа называем соответственно Response

2022-09-29 12:54 UTC, jizis138 commented on features/profile-guest/profile-guest-impl/src/main/java/io/fasthome/fenestram_messenger/profile_guest_impl/presentation/profile_guest/ProfileGuestFragment.kt
> +                    placeholderRes = R.drawable.bg_account_circle
используй R.drawable.common_avatar

2022-09-29 12:54 UTC, jizis138 commented on features/profile-guest/profile-guest-impl/src/main/java/io/fasthome/fenestram_messenger/profile_guest_impl/presentation/profile_guest/ProfileGuestViewModel.kt
> +                )
лучше помещать тело if в фигурные скобки {}, так читаемее

2022-09-30 08:38 UTC, dm1tryM approved these changes

2022-09-30 08:58 UTC, jizis138 approved these changes

2022-09-30 09:12 UTC, merged