GLOBAL-1116 Изменено поведение свайпа
fasthome/Android-Fenestram-Messenger pull request #128
Opened 2022-09-27 15:54 UTC by dm1tryM

2022-09-29 12:10 UTC, jizis138 requested changes

2022-09-29 12:10 UTC, jizis138 commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/messenger/MessengerFragment.kt
> +        Log.d("here", "here")
Нужно удалить

2022-09-29 20:17 UTC, RudakoVladimir approved these changes

2022-09-30 12:45 UTC, vsolodsky approved these changes

2022-09-30 13:29 UTC, merged