GLOBAL-1105/Валидация имени чата
fasthome/Android-Fenestram-Messenger pull request #131
Opened 2022-10-03 07:49 UTC by RudakoVladimir

2022-10-03 10:43 UTC, dm1tryM approved these changes

2022-10-03 10:43 UTC, jizis138 requested changes

2022-10-03 10:43 UTC, jizis138 commented on features/profile-guest/profile-guest-impl/src/main/java/io/fasthome/fenestram_messenger/profile_guest_impl/presentation/profile_guest/ProfileGuestFragment.kt
> +            if (state.profileGuestNameBackground == R.color.dark1)
Завязка на проверку по цвету? Это очень странно

2022-10-03 10:43 UTC, jizis138 commented on features/profile-guest/profile-guest-impl/src/main/java/io/fasthome/fenestram_messenger/profile_guest_impl/presentation/profile_guest/ProfileGuestFragment.kt
> +            if (state.profileGuestNameBackground == R.color.dark1)
Нужно другое решение

2022-10-03 13:04 UTC, vsolodsky approved these changes

2022-10-04 09:59 UTC, jizis138 approved these changes

2022-10-04 11:41 UTC, merged