GLOBAL-1117 Создание приватного чата, поиск контактов при создании чата
fasthome/Android-Fenestram-Messenger pull request #133
Opened 2022-10-04 16:04 UTC by dm1tryM

2022-10-05 09:14 UTC, jizis138 requested changes

2022-10-05 09:14 UTC, jizis138 commented on features/messenger/messenger-impl/src/main/res/layout/dialog_create_chat.xml
> +        android:text="@string/messenger_create_private_chat"
Создать групповой чат

2022-10-05 09:14 UTC, jizis138 commented on features/messenger/messenger-impl/src/main/res/layout/dialog_create_chat.xml
> +        android:drawableLeft="@drawable/ic_create_private_chat"
сейчас иконка вплотную к тексту 
![image](https://user-images.githubusercontent.com/47594134/194024105-e051ac25-afec-4097-a4fe-47b0b121d9e4.png)

2022-10-05 09:15 UTC, vsolodsky approved these changes

2022-10-05 13:09 UTC, DKartovitskii approved these changes

2022-10-05 15:49 UTC, RudakoVladimir approved these changes

2022-10-06 10:30 UTC, DKartovitskii requested changes

2022-10-06 10:30 UTC, DKartovitskii commented on common/uikit/src/main/res/values/button_styles.xml
> +        <item name="android:textSize">14sp</item>
Используй UnelevatedButton как parent, по дизайну тень отсутствует

2022-10-10 07:42 UTC, jizis138 commented on common/uikit/src/main/res/values/button_styles.xml
> +        <item name="android:textSize">14sp</item>
+

2022-10-10 07:44 UTC, merged