GLOBAL-1175 edit message action
fasthome/Android-Fenestram-Messenger pull request #140
Opened 2022-10-10 12:52 UTC by DKartovitskii

2022-10-10 15:19 UTC, jizis138 requested changes

2022-10-10 15:19 UTC, jizis138 commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/ConversationFragment.kt
> +            changeEditMode(null)
контроль логики должен быть из vm

2022-10-10 15:19 UTC, jizis138 commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/ConversationFragment.kt
> +    private fun changeEditMode(selfMessage: ConversationViewItem.Self.Text?) {
можно дать значение по дефолту null здесь, чтобы вызов функции был более лаконичен

2022-10-10 15:19 UTC, jizis138 commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/ConversationFragment.kt
> +    private fun changeEditMode(selfMessage: ConversationViewItem.Self.Text?) {
editMode, это состояние, должно хранится в state

2022-10-10 15:19 UTC, jizis138 commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/ConversationFragment.kt
> +    private fun changeEditMode(selfMessage: ConversationViewItem.Self.Text?) {
соотвественно при каждом renderState editMode будет актуализироваться

2022-10-11 08:51 UTC, DKartovitskii commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/ConversationFragment.kt
> +            changeEditMode(null)
fixed

2022-10-11 08:51 UTC, DKartovitskii commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/ConversationFragment.kt
> +    private fun changeEditMode(selfMessage: ConversationViewItem.Self.Text?) {
fixed

2022-10-11 11:34 UTC, jizis138 approved these changes

2022-10-11 12:37 UTC, RudakoVladimir requested changes
Клавиатура не появляется сразу + фокус при редактировании ставится в начале предложения

2022-10-11 12:39 UTC, jizis138 commented
![image](https://user-images.githubusercontent.com/47594134/195092850-4fbe3de8-73b8-4ad0-bc8c-e470fd6c34a2.png)
вроде должны работать эти экстеншены

2022-10-11 12:53 UTC, RudakoVladimir commented
Ни на эмуляторе, ни на телефоне эти экстеншены не работаю, еще нашел баг: при редактировании сообщения у собеседника присылается новое сообщение, а не изменяется старое

2022-10-11 14:20 UTC, DKartovitskii commented
Fixed

2022-10-12 07:01 UTC, merged