Feature/global 1135 просмотр изображения в чате
fasthome/Android-Fenestram-Messenger pull request #147
Opened 2022-10-12 11:51 UTC by DKartovitskii

2022-10-12 12:49 UTC, jizis138 requested changes

2022-10-12 12:49 UTC, jizis138 commented on common/uikit/src/main/java/io/fasthome/fenestram_messenger/uikit/custom_view/ZoomableImageView.kt
> +    var mMatrix: Matrix? = null
memberValue переменные из java, лучше переимновать их без m

2022-10-12 12:49 UTC, jizis138 commented on common/uikit/src/main/java/io/fasthome/fenestram_messenger/uikit/custom_view/ZoomableImageView.kt
> +    var mMatrix: Matrix? = null
private

2022-10-12 12:49 UTC, jizis138 commented on common/uikit/src/main/java/io/fasthome/fenestram_messenger/uikit/custom_view/ZoomableImageView.kt
> +    get() = onDownSwipe != null
ctrl + alt + L

2022-10-12 12:49 UTC, jizis138 commented on common/uikit/src/main/java/io/fasthome/fenestram_messenger/uikit/custom_view/ZoomableImageView.kt
> +    var mode = NONE
private здесь и все что ниже

2022-10-12 12:49 UTC, jizis138 commented on common/uikit/src/main/java/io/fasthome/fenestram_messenger/uikit/custom_view/ZoomableImageView.kt
> +                    // Log.d("ZoomableImageView", "ACTION_SWIPE_DRAG rawY=${event.rawY}, dY=$dY, alpha=$newAlpha, centerY=$centerY")
ненужный коммент

2022-10-12 12:50 UTC, jizis138 commented
+ изменение длины свайпа для закрытия
+ клик по картинке смещает ее наверх
+ контроль прозрачности фона при свайпе

2022-10-12 13:05 UTC, DKartovitskii commented on common/uikit/src/main/java/io/fasthome/fenestram_messenger/uikit/custom_view/ZoomableImageView.kt
> +    var mMatrix: Matrix? = null
Fixed

2022-10-12 13:05 UTC, DKartovitskii commented on common/uikit/src/main/java/io/fasthome/fenestram_messenger/uikit/custom_view/ZoomableImageView.kt
> +    var mMatrix: Matrix? = null
fixed

2022-10-12 13:06 UTC, DKartovitskii commented on common/uikit/src/main/java/io/fasthome/fenestram_messenger/uikit/custom_view/ZoomableImageView.kt
> +    get() = onDownSwipe != null
fixed

2022-10-12 13:06 UTC, DKartovitskii commented on common/uikit/src/main/java/io/fasthome/fenestram_messenger/uikit/custom_view/ZoomableImageView.kt
> +    var mode = NONE
fixed

2022-10-12 13:06 UTC, DKartovitskii commented on common/uikit/src/main/java/io/fasthome/fenestram_messenger/uikit/custom_view/ZoomableImageView.kt
> +                    // Log.d("ZoomableImageView", "ACTION_SWIPE_DRAG rawY=${event.rawY}, dY=$dY, alpha=$newAlpha, centerY=$centerY")
fixed

2022-10-13 07:42 UTC, RudakoVladimir approved these changes

2022-10-13 07:42 UTC, RudakoVladimir commented on common/component/src/main/java/io/fasthome/component/imageViewer/ImageViewerFragment.kt
> +import io.fasthome.fenestram_messenger.util.toIntAlpha
Unresolved reference: toIntAlpha

2022-10-13 07:43 UTC, DKartovitskii commented on common/component/src/main/java/io/fasthome/component/imageViewer/ImageViewerFragment.kt
> +import io.fasthome.fenestram_messenger.util.toIntAlpha
Уже видел, убрано в [Update ViewUtil.kt](https://github.com/fasthome/Android-Fenestram-Messenger/pull/147/commits/5cd660041e4d4d4aa28482fb0326fa2bc2eec43b)

2022-10-13 07:44 UTC, jizis138 requested changes

2022-10-13 07:44 UTC, jizis138 commented on common/component/src/main/java/io/fasthome/component/imageViewer/ImageViewerFragment.kt
> +import io.fasthome.fenestram_messenger.util.toIntAlpha
не собирает из за лишнего импорта, можно сделать вот так 
![image](https://user-images.githubusercontent.com/47594134/195533904-bb301cfe-7cea-4273-b7be-2770970bade8.png)

2022-10-13 07:47 UTC, DKartovitskii commented on common/component/src/main/java/io/fasthome/component/imageViewer/ImageViewerFragment.kt
> +import io.fasthome.fenestram_messenger.util.toIntAlpha
Убрано в [Update ViewUtil.kt](https://github.com/fasthome/Android-Fenestram-Messenger/pull/147/commits/5cd660041e4d4d4aa28482fb0326fa2bc2eec43b)

2022-10-13 07:51 UTC, DKartovitskii commented on common/component/src/main/java/io/fasthome/component/imageViewer/ImageViewerFragment.kt
> +import io.fasthome.fenestram_messenger.util.toIntAlpha
fixed

2022-10-13 07:51 UTC, DKartovitskii commented on common/component/src/main/java/io/fasthome/component/imageViewer/ImageViewerFragment.kt
> +import io.fasthome.fenestram_messenger.util.toIntAlpha
fixed

2022-10-13 07:56 UTC, jizis138 approved these changes

2022-10-13 08:02 UTC, merged