Feature GLOBAL-1175, GLOBAL-1257 плашки "Изменено" на receive и group сообщениях, изменен цвет
fasthome/Android-Fenestram-Messenger pull request #148
Opened 2022-10-12 12:23 UTC by DKartovitskii

2022-10-12 12:57 UTC, jizis138 requested changes

2022-10-12 12:57 UTC, jizis138 commented on features/messenger/messenger-impl/src/main/res/layout/conversation_item_self_text.xml
> +        android:layout_marginTop="16dp"
отступы сверху и снизу ставятся через декоратор, отсюда надо убрать

2022-10-12 12:57 UTC, jizis138 commented on features/messenger/messenger-impl/src/main/res/layout/conversation_item_self_text.xml
> +        android:layout_marginTop="16dp"
+ сейчас отправленное сообщение кажется больше полученного по высоте, ориентируемся на высоту полученного

2022-10-12 13:27 UTC, DKartovitskii commented on features/messenger/messenger-impl/src/main/res/layout/conversation_item_self_text.xml
> +        android:layout_marginTop="16dp"
fixed

2022-10-13 07:48 UTC, RudakoVladimir approved these changes

2022-10-13 08:13 UTC, DKartovitskii commented on features/messenger/messenger-impl/src/main/res/layout/conversation_item_self_text.xml
> +        android:layout_marginTop="16dp"
fixed

2022-10-13 08:18 UTC, jizis138 approved these changes

2022-10-13 08:20 UTC, jizis138 requested changes
Сообщения сейчас не редактируются

2022-10-13 10:55 UTC, jizis138 approved these changes

2022-10-13 11:17 UTC, merged