GLOBAL-1211 Исправлен баг при редактировании группового чата через popup меню
fasthome/Android-Fenestram-Messenger pull request #153
Opened 2022-10-13 13:52 UTC by RudakoVladimir

…pup меню

2022-10-13 14:44 UTC, jizis138 requested changes

2022-10-13 14:44 UTC, jizis138 commented on features/profile-guest/profile-guest-impl/src/main/java/io/fasthome/fenestram_messenger/profile_guest_impl/presentation/profile_guest/ProfileGuestViewModel.kt
> +        sendEvent(ProfileGuestEvent.SetProfileName(PrintableText.Raw(params.userName)))
зачем здесь sendEvent, если имя задается уже через стейт?

2022-10-13 15:29 UTC, DKartovitskii approved these changes

2022-10-13 15:53 UTC, RudakoVladimir commented on features/profile-guest/profile-guest-impl/src/main/java/io/fasthome/fenestram_messenger/profile_guest_impl/presentation/profile_guest/ProfileGuestViewModel.kt
> +        sendEvent(ProfileGuestEvent.SetProfileName(PrintableText.Raw(params.userName)))
Я так сделал, потому что имя не изменяется, если стоит editMode. Альтернативный вариант был добавить в стейт флаг isInitialState. Либо в onViewCreated фрагмента в первый раз присвоить имя. Какой вариант лучше?

2022-10-14 07:19 UTC, jizis138 commented on features/profile-guest/profile-guest-impl/src/main/java/io/fasthome/fenestram_messenger/profile_guest_impl/presentation/profile_guest/ProfileGuestViewModel.kt
> +        sendEvent(ProfileGuestEvent.SetProfileName(PrintableText.Raw(params.userName)))
createInitialState и нужен для того, чтобы задать начальные значения, оба предложенные варианты не будут верны, подумай как еще это обойти

2022-10-19 07:18 UTC, jizis138 approved these changes

2022-10-19 07:33 UTC, merged