GLOBAL-974 Отображение своего контакта на экране контактов
fasthome/Android-Fenestram-Messenger pull request #154
Opened 2022-10-13 15:10 UTC by RudakoVladimir

2022-10-14 07:14 UTC, jizis138 requested changes

2022-10-14 07:14 UTC, jizis138 commented on features/contacts/contacts-impl/src/main/java/io/fasthome/fenestram_messenger/contacts_impl/presentation/contacts/mapper/ContactsMapper.kt
> +            if (contact.phone == selfUserPhone || user.phone == selfUserPhone) " (вы)" else ""
(вы) должно храниться в ресурсах, используй Formatting strings

2022-10-17 06:26 UTC, DKartovitskii approved these changes

2022-10-17 16:35 UTC, jizis138 approved these changes

2022-10-17 17:07 UTC, merged