Feature/GLOBAL-1094 Статус "Прочитано", количество непрочитанных сообщений, анимация статуса "Печатает"
fasthome/Android-Fenestram-Messenger pull request #158
Opened 2022-10-25 13:23 UTC by RudakoVladimir

2022-10-26 10:54 UTC, jizis138 requested changes

2022-10-26 10:54 UTC, jizis138 commented on features/messenger/messenger-impl/src/main/res/layout/fragment_conversation.xml
> +    <!--        android:id="@+id/pending_messages2"-->
это нужно?

2022-10-31 07:38 UTC, DKartovitskii approved these changes

2022-11-01 07:27 UTC, jizis138 approved these changes

2022-11-01 07:27 UTC, merged