GLOBAL-1266/Ссылки в сообщениях
fasthome/Android-Fenestram-Messenger pull request #160
Opened 2022-11-01 17:40 UTC by RudakoVladimir

2022-11-02 10:23 UTC, DKartovitskii requested changes
1. не предусмотрен кейс с доменом - **.рф** 
2. 4123567890 - принимает как номер телефона
3. Баг с попыткой открытия меню с действиями у сообщения, удерживая ссылку (3 вибрации, через раз открывается меню)

2022-11-02 10:23 UTC, DKartovitskii commented on common/util/src/main/java/io/fasthome/fenestram_messenger/util/links/Extension.kt
> +        })
Наверное `.setOnLongClickListener` нужно везде убрать, зачем они нужны?)

2022-11-02 10:35 UTC, DKartovitskii requested changes

2022-11-02 10:35 UTC, DKartovitskii commented on common/util/src/main/java/io/fasthome/fenestram_messenger/util/links/Link.kt
> +    }
Не используемые методы, они нужны?

2022-11-02 10:35 UTC, DKartovitskii commented on common/util/src/main/java/io/fasthome/fenestram_messenger/util/links/Link.kt
> +    }
Не используемые методы, они нужны?

2022-11-02 10:35 UTC, DKartovitskii commented on common/util/src/main/java/io/fasthome/fenestram_messenger/util/links/Link.kt
> +    }
Зачем 2 функции, думаю что можно сделать одну, убрать интерфейс, а сделать.
var clickListener: ((text: String) -> Unit)? = null

2022-11-02 10:35 UTC, DKartovitskii commented on common/util/src/main/java/io/fasthome/fenestram_messenger/util/links/Link.kt
> +    }
То же самое, что и с setOnClickListener

2022-11-02 10:35 UTC, DKartovitskii commented on common/util/src/main/java/io/fasthome/fenestram_messenger/util/links/Link.kt
> +    }
Можно ли убрать цвет ссылки в res?

2022-11-02 10:44 UTC, DKartovitskii requested changes

2022-11-02 10:44 UTC, DKartovitskii commented on common/util/src/main/java/io/fasthome/fenestram_messenger/util/links/Extension.kt
> +    } catch (e: Exception) {
Текст перенести в strings.xml, перевести на русский)

2022-11-02 10:47 UTC, DKartovitskii requested changes

2022-11-02 10:47 UTC, DKartovitskii commented on common/util/src/main/java/io/fasthome/fenestram_messenger/util/links/Link.kt
> +@Suppress("MemberVisibilityCanBePrivate")
Нужна ли тут аннотация?

2022-11-02 18:22 UTC, RudakoVladimir commented on common/util/src/main/java/io/fasthome/fenestram_messenger/util/links/Link.kt
> +    }
Underline оставил, потому что ссылки могут быть без подчеркивания

2022-11-02 18:23 UTC, RudakoVladimir commented on common/util/src/main/java/io/fasthome/fenestram_messenger/util/links/Link.kt
> +    }
Можно, но тогда цвет придется выставлять извне класса Link, сделать так?

2022-11-03 06:58 UTC, DKartovitskii commented on common/util/src/main/java/io/fasthome/fenestram_messenger/util/links/Link.kt
> +    }
Хорошо, оставь пока как есть

2022-11-07 11:56 UTC, jizis138 approved these changes

2022-11-09 07:20 UTC, DKartovitskii approved these changes

2022-11-09 07:54 UTC, merged