GLOBAL-1454 Реализован ответ свайпом в чате (кроме документов)
fasthome/Android-Fenestram-Messenger pull request #163
Opened 2022-11-09 19:09 UTC by jizis138

2022-11-10 12:44 UTC, DKartovitskii requested changes

2022-11-10 12:44 UTC, DKartovitskii commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/adapter/ConversationAdapter.kt
> +            }
Чуть ниже вроде ещё один вызов onImageClicked, нужен?

2022-11-10 13:13 UTC, jizis138 commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/adapter/ConversationAdapter.kt
> +            }
тот что ниже не работает, его уберу ага

2022-11-11 08:26 UTC, jizis138 commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/adapter/ConversationAdapter.kt
> +            }
fixed

2022-11-11 16:50 UTC, merged