GLOBAL-1173 возможность обращения к определенному участнику в чате
fasthome/Android-Fenestram-Messenger pull request #167
Opened 2022-11-15 13:06 UTC by DKartovitskii

2022-11-15 13:51 UTC, jizis138 requested changes

2022-11-15 13:51 UTC, jizis138 commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/ConversationFragment.kt
> +        rvChatUserTags.layoutManager =
можно указывать lm в разметке, так код на строчку чище

2022-11-15 13:51 UTC, jizis138 commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/ConversationFragment.kt
> +            if (!text.isNullOrEmpty()) {
почему бы эту проверку не вынести во viewModel?

2022-11-16 06:44 UTC, DKartovitskii commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/ConversationFragment.kt
> +        rvChatUserTags.layoutManager =
fixed

2022-11-16 11:26 UTC, DKartovitskii commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/ConversationFragment.kt
> +            if (!text.isNullOrEmpty()) {
fixed

2022-11-16 17:25 UTC, merged