GLOBAL-1761 Исправлены статусы
fasthome/Android-Fenestram-Messenger pull request #205
Opened 2022-12-08 22:02 UTC by dm1tryM

2022-12-09 07:13 UTC, DKartovitskii requested changes

2022-12-09 07:13 UTC, DKartovitskii commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/mapper/ConversationMapper.kt
>          UserStatus.Offline -> {
UserStatus.toPrintableText и так вызывается у UserStatus, и получается если UserStatus.Offline, то внутри мы ещё раз проверяем онлайн?

2022-12-09 10:01 UTC, dm1tryM commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/mapper/ConversationMapper.kt
>          UserStatus.Offline -> {
Сейчас для групп разницы нет (UserStatus.Online или UserStatus.Offline мы используем), в любом случае внутри функции мы проходимся по списку и считаем сколько людей в группе онлайн. Однако, практически во всех местах мы вызываем toPrintableText  для UserStatus.Offline без всяких проверок, поэтому я добавил в одном месте (внутри функции) проверку, если чат не групповой, то просто проверяем статус пользователя (т.е. аналогично групповому чату: если группа - считаем количество людей онлайн, если личный чат - то выводим то, что пришло с бэка). В таком случае думаю подправить UserStatus (оставить только Typing и OnlineStatus, например). И если вызываем для Status.Typing - то выводим одно, если для Statuse.OnlineStatus - проверяем группа или личный чат, а далее либо считаем количество людей онлайн, либо сразу смотрим статус пользователя.

2022-12-09 11:41 UTC, DKartovitskii commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/mapper/ConversationMapper.kt
>          UserStatus.Offline -> {
Возможно как раз UserStatus.OnlineStatus хорошая идея, как лучше @jizis138 ?

2022-12-16 07:12 UTC, jizis138 approved these changes

2022-12-16 07:13 UTC, merged