GLOBAL-1660 Исправление дублирования контактов при добавлении
fasthome/Android-Fenestram-Messenger pull request #212
Opened 2022-12-15 13:04 UTC by RudakoVladimir

Мержить после GLOBAL 1771

2022-12-16 08:41 UTC, dm1tryM requested changes

2022-12-16 08:41 UTC, dm1tryM commented on features/contacts/contacts-impl/src/main/java/io/fasthome/fenestram_messenger/contacts_impl/data/service/ContactsService.kt
> +                path = environment.endpoints.baseUrl + "api/v2/contacts",
Можно использовать StorageUrlConverter

2022-12-16 08:41 UTC, dm1tryM commented on features/contacts/contacts-impl/src/main/java/io/fasthome/fenestram_messenger/contacts_impl/data/service/ContactsService.kt
> +            path = environment.endpoints.baseUrl + "api/v2/contacts",
Можно использовать StorageUrlConverter

2022-12-18 21:03 UTC, jizis138 commented on features/contacts/contacts-impl/src/main/java/io/fasthome/fenestram_messenger/contacts_impl/data/service/ContactsService.kt
> +            path = environment.endpoints.baseUrl + "api/v2/contacts",
Нет, нельзя, это ручка на v2 для контактов, чтобы не менять baseUrl сделано так

2022-12-18 21:03 UTC, jizis138 approved these changes

2022-12-19 07:30 UTC, RudakoVladimir commented on features/contacts/contacts-impl/src/main/java/io/fasthome/fenestram_messenger/contacts_impl/data/service/ContactsService.kt
> +                path = environment.endpoints.baseUrl + "api/v2/contacts",
Здесь нужно поменять версию api с v1 на v2 только для этой ручки, проще способа не нашел

2022-12-19 07:51 UTC, dm1tryM approved these changes

2022-12-19 07:52 UTC, merged