GLOBAL-861 Изменение имени контакта через ProfileGuest
fasthome/Android-Fenestram-Messenger pull request #213
Opened 2022-12-15 14:18 UTC by RudakoVladimir

Мержить после GLOBAL-1660

2022-12-16 08:41 UTC, dm1tryM requested changes

2022-12-16 08:41 UTC, dm1tryM commented on features/contacts/contacts-impl/src/main/java/io/fasthome/fenestram_messenger/contacts_impl/data/ContactsLoader.kt
> +                .withValue(CommonDataKinds.Phone.NUMBER, mobileNumber.replace(" ", "").replace("-", ""))
Сейчас в приложении используется PhoneEditText, и в нем есть метод getPhoneNumberFiltered()

2022-12-16 08:41 UTC, dm1tryM commented on features/contacts/contacts-impl/src/main/java/io/fasthome/fenestram_messenger/contacts_impl/data/service/ContactsService.kt
> +            path = environment.endpoints.baseUrl + "api/v2/contacts",
Можно использовать StorageUrlConverter

2022-12-18 21:13 UTC, jizis138 commented on features/contacts/contacts-impl/src/main/java/io/fasthome/fenestram_messenger/contacts_impl/data/service/ContactsService.kt
> +            path = environment.endpoints.baseUrl + "api/v2/contacts",
StorageUrlConverter используется для конвертации path файлов в url загрузки

2022-12-18 21:13 UTC, jizis138 commented on features/contacts/contacts-impl/src/main/java/io/fasthome/fenestram_messenger/contacts_impl/presentation/contacts/ContactsViewModel.kt
> +            is ContactAddNavigationContract.ContactAddResult.Success -> {}
нагляднее писать Unit вместо {}

2022-12-18 21:13 UTC, jizis138 commented on features/profile-guest/profile-guest-impl/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.WRITE_CONTACTS" />
этот пермишен уже есть в contacts-impl, давай все пермишены хранить в манифесте уровня app для наглядности

2022-12-18 21:13 UTC, jizis138 commented on features/contacts/contacts-impl/src/main/java/io/fasthome/fenestram_messenger/contacts_impl/domain/logic/ContactsInteractor.kt
> +        contactsRepo.uploadContacts(localContacts)
а Юра не сделал все таки отдельной ручки на апдейт контакта? Может быть есть решение лучше, чем перезагрузка всех контактов

2022-12-19 07:33 UTC, RudakoVladimir commented on features/contacts/contacts-impl/src/main/java/io/fasthome/fenestram_messenger/contacts_impl/domain/logic/ContactsInteractor.kt
> +        contactsRepo.uploadContacts(localContacts)
да, под новой ручкой он тогда имел ввиду v2 старой ручки

2022-12-19 07:35 UTC, RudakoVladimir commented on features/contacts/contacts-impl/src/main/java/io/fasthome/fenestram_messenger/contacts_impl/data/service/ContactsService.kt
> +            path = environment.endpoints.baseUrl + "api/v2/contacts",
см. PR 1660

2022-12-19 07:51 UTC, dm1tryM approved these changes

2022-12-19 08:20 UTC, merged