GLOBAL-1795 Отображение текста пересланного сообщения в зависимости о…
fasthome/Android-Fenestram-Messenger pull request #230
Opened 2022-12-27 17:00 UTC by jizis138

…т типа файла

2022-12-27 22:21 UTC, dm1tryM approved these changes

2022-12-28 07:24 UTC, DKartovitskii commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/ConversationFragment.kt
> +                attachedAdapter.items = state.inputMessageMode.attachedFiles.filter {  }
Пустой .filter { }, не собирается проект

2022-12-28 07:26 UTC, DKartovitskii requested changes

2022-12-28 07:26 UTC, DKartovitskii commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/ConversationFragment.kt
> +                attachedAdapter.items = state.inputMessageMode.attachedFiles.filter {  }
Пустой .filter { }, не собирается проект

2022-12-28 13:06 UTC, jizis138 commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/ConversationFragment.kt
> +                attachedAdapter.items = state.inputMessageMode.attachedFiles.filter {  }
++

2022-12-28 13:42 UTC, DKartovitskii approved these changes

2022-12-28 13:42 UTC, merged