#8576216 image bottom sheet
fasthome/Android-Fenestram-Messenger pull request #269
Opened 2023-02-02 09:17 UTC by DKartovitskii

2023-02-06 13:46 UTC, jizis138 requested changes

2023-02-06 13:46 UTC, jizis138 commented on common/component/src/main/java/io/fasthome/component/gallery/GalleryRepository.kt
> +    fun getGalleryImages(page: Int, itemsPerPage: Int = GalleryRepositoryImpl.IMAGES_COUNT_ON_PAGE): CallResult<List<GalleryImage>>
функции должны быть suspend

2023-02-06 13:46 UTC, jizis138 commented on common/component/src/main/java/io/fasthome/component/gallery/GalleryRepositoryImpl.kt
> +        try {
по идее здесь try catch не нужен, в случае catch будет CallResult.Error

2023-02-06 13:46 UTC, jizis138 commented on common/component/src/main/java/io/fasthome/component/gallery/GalleryRepositoryImpl.kt
> +            Log.e("TAG", e.message.toString())
Логи тоже не нужны

2023-02-06 13:46 UTC, jizis138 commented on common/component/src/main/java/io/fasthome/component/gallery/GalleryRepositoryImpl.kt
> +        Log.d("GalleryOperationsImpl",
и тут

2023-02-06 13:46 UTC, jizis138 commented on common/component/src/main/java/io/fasthome/component/gallery/GalleryRepositoryImpl.kt
> +            Log.d("GalleryOperationsImpl",
посмотри в общем везде где логи оставил

2023-02-06 13:46 UTC, jizis138 commented on common/component/src/main/java/io/fasthome/component/imageViewer/ImageViewerFragment.kt
> +                binding.tvCounter.text = getString(R.string.common_value_from_value_ph,
это должно прокидываться через vm, оттуда приходить через event

2023-02-06 13:46 UTC, jizis138 commented on common/component/src/main/java/io/fasthome/component/imageViewer/ImageViewerFragment.kt
> +                binding.tvCounter.text = getString(R.string.common_value_from_value_ph,
как и все что ниже

2023-02-06 13:46 UTC, jizis138 commented on common/component/src/main/res/layout/fragment_image_viewer.xml
> +    android:elevation="100dp"
зачем такая высота?

2023-02-06 13:46 UTC, jizis138 commented on common/core/src/main/java/io/fasthome/fenestram_messenger/core/di/CoreModule.kt
> +            BottomViewAction<String>()
это еще нужно?

2023-02-06 13:46 UTC, jizis138 commented on common/presentation/base/src/main/java/io/fasthome/fenestram_messenger/presentation/base/ui/BaseBottomSheetFragment.kt
> +//        binding.root.background.alpha =
можно удалить

2023-02-06 13:46 UTC, jizis138 commented on common/presentation/base/src/main/java/io/fasthome/fenestram_messenger/presentation/base/ui/BottomSheetFragmentWithButton.kt
> +        this.onDestroy()
так не стоит делать

2023-02-06 13:46 UTC, jizis138 commented on common/presentation/base/src/main/java/io/fasthome/fenestram_messenger/presentation/base/ui/BottomSheetFragmentWithButton.kt
> +                        is FileSelectorButtonEvent.SheetCloseEvent -> {
вроде как теперь этот ивент не нужен

2023-02-06 13:46 UTC, jizis138 commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/ConversationViewModel.kt
> +            val chunkedFiles = allFiles.chunked(10)
10 вынести в константу

2023-02-06 13:46 UTC, jizis138 commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/file_selector/FileSelectorAdapter.kt
> +                val anim = if (binding.cbSelect.isChecked) AnimationUtil.getScaleAnimation(
точнее в будущий FileSelectorViewItem

2023-02-06 13:46 UTC, jizis138 commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/file_selector/FileSelectorFragment.kt
> +            if (image.isChecked) selectedList.add(UriLoadableContent(image.uri)) else selectedList.removeIf { (it as? UriLoadableContent)?.uri == image.uri }
вот это тоже должно происходить в vm добавление/удаление

2023-02-06 13:46 UTC, jizis138 commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/file_selector/FileSelectorFragment.kt
> +    private var recyclerY = 0f
переменные храним вверху класса

2023-02-06 13:46 UTC, jizis138 commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/file_selector/FileSelectorNavigationContract.kt
> +    NavigationContract<NoParams, FileSelectorNavigationContract.Result>(FileSelectorBottomFragment::class) {
Если прикрепить 3 изображения, потом еще раз зайти на экран, то они не будут выбраны. Нужно это обрабатывать и присылать сюда выбранные картинки и выделять

2023-02-06 13:46 UTC, jizis138 commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/file_selector/FileSelectorViewModel.kt
> +            getCachedSelectedId = { null },
можно сделать еще один loadDataHelper и удалить ненужные функции

2023-02-06 13:46 UTC, jizis138 commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/file_selector/FileSelectorViewModel.kt
> +       // exitWithResult(FileSelectorNavigationContract.createResult(FileSelectorNavigationContract.Result.OpenGallery))
sendActionToBottomView больше не нужен

2023-02-06 14:51 UTC, DKartovitskii commented on common/presentation/base/src/main/java/io/fasthome/fenestram_messenger/presentation/base/ui/BottomSheetFragmentWithButton.kt
> +        this.onDestroy()
Случайно видимо, проверял и не убрал, fixed

2023-02-06 15:28 UTC, DKartovitskii commented on common/core/src/main/java/io/fasthome/fenestram_messenger/core/di/CoreModule.kt
> +            BottomViewAction<String>()
Нужно, но поменял тип на FileSelectorButtonEvent

2023-02-06 15:30 UTC, DKartovitskii commented on common/component/src/main/res/layout/fragment_image_viewer.xml
> +    android:elevation="100dp"
Убрано, осталось после попыток убрать BottomSheetDialog под ImageViewer

2023-02-06 15:32 UTC, DKartovitskii commented on common/presentation/base/src/main/java/io/fasthome/fenestram_messenger/presentation/base/ui/BottomSheetFragmentWithButton.kt
> +                        is FileSelectorButtonEvent.SheetCloseEvent -> {
Убран

2023-02-06 15:32 UTC, DKartovitskii commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/ConversationViewModel.kt
> +                selectFromCamera()
Заменил

2023-02-06 15:33 UTC, DKartovitskii commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/ConversationViewModel.kt
> +            val chunkedFiles = allFiles.chunked(10)
Вынес

2023-02-06 15:36 UTC, DKartovitskii commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/ConversationViewModel.kt
> +//        sendEvent(ConversationEvent.ShowSelectFromDialog(attachedContent =
Убрано

2023-02-06 15:37 UTC, DKartovitskii commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/file_selector/FileSelectorAdapter.kt
> +                Log.d("SelectFromConversationAdapter", "onImageClick, pos: ${item.cursorPosition}")
Убрано

2023-02-06 15:39 UTC, DKartovitskii commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/file_selector/FileSelectorFragment.kt
> +            vm.onBackPressed()
Убрано

2023-02-06 15:40 UTC, DKartovitskii commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/file_selector/FileSelectorFragment.kt
> +    private var recyclerY = 0f
Переместил

2023-02-06 15:42 UTC, DKartovitskii commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/file_selector/FileSelectorViewModel.kt
> +       // exitWithResult(FileSelectorNavigationContract.createResult(FileSelectorNavigationContract.Result.OpenGallery))
Убрано

2023-02-06 15:43 UTC, DKartovitskii commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/file_selector/FileSelectorViewModel.kt
> +       // exitWithResult(FileSelectorNavigationContract.createResult(FileSelectorNavigationContract.Result.OpenGallery))
SheetCloseEvent не нужен, а sendActionToBottomView требуется для обновления количества выбранных изображений на кнопке. SheetCloseEvent убран

2023-02-06 15:51 UTC, DKartovitskii commented on common/component/src/main/java/io/fasthome/component/gallery/GalleryRepository.kt
> +    fun getGalleryImages(page: Int, itemsPerPage: Int = GalleryRepositoryImpl.IMAGES_COUNT_ON_PAGE): CallResult<List<GalleryImage>>
Исправил

2023-02-06 15:51 UTC, DKartovitskii commented on common/component/src/main/java/io/fasthome/component/gallery/GalleryRepositoryImpl.kt
> +        try {
Убрал

2023-02-06 15:51 UTC, DKartovitskii commented on common/component/src/main/java/io/fasthome/component/gallery/GalleryRepositoryImpl.kt
> +            Log.e("TAG", e.message.toString())
Убрано

2023-02-06 15:52 UTC, DKartovitskii commented on common/component/src/main/java/io/fasthome/component/gallery/GalleryRepositoryImpl.kt
> +        Log.d("GalleryOperationsImpl",
Убрано

2023-02-06 15:52 UTC, DKartovitskii commented on common/component/src/main/java/io/fasthome/component/gallery/GalleryRepositoryImpl.kt
> +            Log.d("GalleryOperationsImpl",
Убрал везде

2023-02-06 16:33 UTC, DKartovitskii commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/ConversationViewModel.kt
> +            val attachedImages = galleryImages.map { AttachedFile.Image(it) }
moved

2023-02-06 16:36 UTC, DKartovitskii commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/ConversationViewModel.kt
> +                ((state.inputMessageMode as? InputMessageMode.Default)?.attachedFiles
ready

2023-02-06 16:38 UTC, DKartovitskii commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/ConversationViewModel.kt
> +                    val fileMessage = createDocumentMessage(emptyList(), files.map { it.file })
готово

2023-02-06 16:44 UTC, DKartovitskii commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/file_selector/FileSelectorFragment.kt
> +    private val selectedList = mutableListOf<Content>()
moved

2023-02-06 16:44 UTC, DKartovitskii commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/file_selector/FileSelectorFragment.kt
> +            if (image.isChecked) selectedList.add(UriLoadableContent(image.uri)) else selectedList.removeIf { (it as? UriLoadableContent)?.uri == image.uri }
перенес

2023-02-06 17:28 UTC, DKartovitskii commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/file_selector/FileSelectorAdapter.kt
> +    onCheckImage: (image: GalleryImage) -> Unit,
готово

2023-02-06 17:35 UTC, DKartovitskii commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/file_selector/FileSelectorAdapter.kt
> +                val anim = if (binding.cbSelect.isChecked) AnimationUtil.getScaleAnimation(
ready

2023-02-06 17:37 UTC, DKartovitskii commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/file_selector/FileSelectorViewModel.kt
> +            getCachedSelectedId = { null },
добавил аргументы по умолчанию

2023-02-06 17:55 UTC, DKartovitskii commented on common/component/src/main/java/io/fasthome/component/imageViewer/ImageViewerFragment.kt
> +                binding.tvCounter.text = getString(R.string.common_value_from_value_ph,
fixed

2023-02-07 07:46 UTC, DKartovitskii commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/file_selector/FileSelectorNavigationContract.kt
> +    NavigationContract<NoParams, FileSelectorNavigationContract.Result>(FileSelectorBottomFragment::class) {
Исправлено

2023-02-07 09:42 UTC, jizis138 requested changes

2023-02-07 13:11 UTC, DKartovitskii commented on common/component/src/main/java/io/fasthome/component/imageViewer/ImageViewerViewModel.kt
> +    private fun loadBeforeImages(cursorPosition: Int, needScrollAfterSet: Boolean = false) {
Убрано после добавления PagingData

2023-02-07 13:31 UTC, DKartovitskii commented on common/component/src/main/java/io/fasthome/component/imageViewer/ImageViewerViewModel.kt
> +    private fun loadBeforeImages(cursorPosition: Int, needScrollAfterSet: Boolean = false) {
Больше не требуются, заменил на PagingData

2023-02-09 08:46 UTC, jizis138 approved these changes

2023-02-09 08:46 UTC, merged