HC-8890827 Реализованы реакции
fasthome/Android-Fenestram-Messenger pull request #273
Opened 2023-02-09 15:09 UTC by RudakoVladimir

2023-02-10 08:57 UTC, jizis138 commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/mapper/ConversationMapper.kt
> +        else -> error("Unexpected View Item $oldViewItem !")
давай откажемся от вызова exception чтобы избежать лишних крашей, заполни пустым списком хотя бы

2023-02-13 11:18 UTC, RudakoVladimir commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/mapper/ConversationMapper.kt
> +        else -> error("Unexpected View Item $oldViewItem !")
Исправлено

2023-02-13 14:29 UTC, DKartovitskii requested changes

2023-02-14 11:59 UTC, RudakoVladimir commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/ConversationViewModel.kt
>                      val selfUserId = messengerInteractor.getUserId()
Исправлено

2023-02-14 11:59 UTC, RudakoVladimir commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/ConversationViewModel.kt
> +                            it.permittedReactions.map { reaction -> PermittedReactionViewItem(reaction) }
Исправлено

2023-02-14 11:59 UTC, RudakoVladimir commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/ConversationViewModel.kt
>              updateState { state ->
Исправлено

2023-02-14 12:00 UTC, RudakoVladimir commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/adapter/ReactionsAdapter.kt
> +        }
Нужно проверить

2023-02-14 12:00 UTC, RudakoVladimir commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/adapter/ReactionsAdapter.kt
> +            root.backgroundTintList = ColorStateList.valueOf(context.resources.color(item.reactionBackground))
Нужно проверить

2023-02-17 09:45 UTC, merged