GLOBAL-835 Отправка SMS при первом вводе номера
fasthome/Android-Fenestram-Messenger pull request #55
Opened 2022-09-07 05:52 UTC by dm1tryM

2022-09-07 07:00 UTC, jizis138 requested changes

2022-09-07 07:00 UTC, jizis138 commented on features/auth/auth-impl/src/main/java/io/fasthome/fenestram_messenger/auth_impl/presentation/welcome/WelcomeViewModel.kt
> +                        checkCodeLauncher.launch(CodeNavigationContract.Params("+7$phoneNumber"))
Сейчас наблюдается некая подторможенность в UI, потому что мы дожидаемся ответа что код отправился. Быстрое решение - показать загрузку, пока отправляется код

2022-09-09 05:09 UTC, vsolodsky approved these changes

2022-09-09 13:43 UTC, RudakoVladimir approved these changes

2022-09-12 04:50 UTC, jizis138 approved these changes

2022-09-12 08:07 UTC, dm1tryM commented
GLOBAL-835 Отправка SMS при первом вводе номера

2022-09-12 08:08 UTC, merged