GLOBAL-857 Исправление багов: 3, 4, 8, 10, 11, 13
fasthome/Android-Fenestram-Messenger pull request #56
Opened 2022-09-07 05:53 UTC by dm1tryM

2022-09-07 07:03 UTC, jizis138 requested changes

2022-09-07 07:03 UTC, jizis138 commented on features/contacts/contacts-impl/src/main/res/layout/include_edit_text.xml
> +    android:digits="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZабвгдеёжзийклмнопрстуфхцчшщъыьэюяАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ"
Используй Regex

2022-09-08 07:23 UTC, jizis138 approved these changes

2022-09-08 07:44 UTC, RudakoVladimir approved these changes

2022-09-09 08:16 UTC, vsolodsky approved these changes

2022-09-12 04:15 UTC, merged