GLOBAL-836 Исправлены баги 1, 2, 3, 6, 7
fasthome/Android-Fenestram-Messenger pull request #57
Opened 2022-09-07 08:37 UTC by RudakoVladimir

2022-09-07 15:33 UTC, jizis138 requested changes

2022-09-07 15:33 UTC, jizis138 commented on features/auth/auth-impl/build.gradle.kts
> +    implementation("io.michaelrocks:libphonenumber-android:8.12.52")
зависимости храним в Deps

2022-09-07 15:33 UTC, jizis138 commented on features/auth/auth-impl/src/main/java/io/fasthome/fenestram_messenger/auth_impl/presentation/welcome/PhoneNumberInputManager.kt
> +        } ?: "Некорректный код страны"
Изначально введена +7, но отображается как Некорректный код страны

2022-09-07 15:33 UTC, jizis138 commented on features/auth/auth-impl/src/main/res/layout/fragment_welcome.xml
> +        android:digits="0123456789+ -()"
Лучше использовать Regex

2022-09-09 05:31 UTC, vsolodsky approved these changes

2022-09-11 20:19 UTC, dm1tryM approved these changes

2022-09-12 04:50 UTC, jizis138 approved these changes

2022-09-12 08:11 UTC, merged