GLOBAL-862 Добавлена возможность удаления чата
fasthome/Android-Fenestram-Messenger pull request #70
Opened 2022-09-14 14:43 UTC by dm1tryM

2022-09-15 05:23 UTC, jizis138 requested changes

2022-09-15 05:23 UTC, jizis138 commented on common/core/src/main/res/layout/dialog_delete_chat.xml
> +        android:textAppearance="@style/Text"
Если в button_styles.xml нету подходящий стилей, то лучше завести их там

2022-09-15 05:23 UTC, jizis138 commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/data/service/MessengerService.kt
> +        return DeleteMapper.responseToDeleteChatResult(response)
маппер здесь и DeleteChatResult здесь лишний, т.к. никаких данных в себе не несут.

2022-09-15 05:23 UTC, jizis138 commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/domain/logic/MessengerInteractor.kt
> +    suspend fun deleteChat(id: Long) = messageRepo.deleteChat(id).onSuccess { }
.onSuccess { } здесь не нужен

2022-09-15 05:23 UTC, jizis138 commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/ConversationFragment.kt
> +                popupmenu.showAsDropDown(binding.dropdownMenu)
Создание popup лучше вынести в отдельный файл, чтобы был универсальным к использованию

2022-09-15 05:23 UTC, jizis138 commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/ConversationFragment.kt
> +                val viewMenu = inflater.inflate(R.layout.menu, null)
для viewMenu можно же использовать Binding? Тогда не придется ниже использовать findViewById

2022-09-15 05:23 UTC, jizis138 commented on features/profile-guest/profile-guest-impl/src/main/java/io/fasthome/fenestram_messenger/profile_guest_impl/data/service/ProfileGuestService.kt
> +    suspend fun deleteChat(id: Long): DeleteChatResult {
Продублировал из MessengerService? Для профиля удаление можно сделать через MessengerFeature, где будет будет использован MessengerService.deleteChat()

2022-09-15 05:23 UTC, jizis138 commented on features/profile-guest/profile-guest-impl/src/main/java/io/fasthome/fenestram_messenger/profile_guest_impl/domain/entity/DeleteChatResult.kt
> +sealed class DeleteChatResult {
Ненужный класс

2022-09-15 05:23 UTC, jizis138 commented on features/profile-guest/profile-guest-impl/src/main/java/io/fasthome/fenestram_messenger/profile_guest_impl/domain/repo/ProfileGuestRepo.kt
> +interface ProfileGuestRepo {
Ненужный, если прокинешь удаление через фичу

2022-09-15 05:32 UTC, jizis138 commented
Диалог без отступов 
![image](https://user-images.githubusercontent.com/47594134/190322227-4bf6d155-191a-45f0-b08c-7ce9aa646c66.png)

2022-09-15 05:37 UTC, jizis138 requested changes

2022-09-15 05:37 UTC, jizis138 commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/messenger/MessengerViewModel.kt
> +                    fetchChats()
если выгружать заново весь список, то ui сильно скачет. Лучше удалить нужный элемент из state.messengerViewItems

2022-09-15 05:37 UTC, jizis138 commented on features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/messenger/MessengerViewModel.kt
> +                fetchChats()
тоже самое со скачком, можно передать в ChatDeleted() соответственный id, и удалить из state этот итем

2022-09-15 05:37 UTC, jizis138 commented on features/profile-guest/profile-guest-impl/src/main/res/layout/fragment_profile_guest.xml
> +        <androidx.appcompat.widget.AppCompatButton
Не по макету
![image](https://user-images.githubusercontent.com/47594134/190322855-c32f17fd-9853-4fd8-bffc-739779de9953.png)

2022-09-15 12:36 UTC, vsolodsky approved these changes

2022-09-15 14:51 UTC, RudakoVladimir approved these changes

2022-09-16 13:57 UTC, jizis138 approved these changes

2022-09-16 15:57 UTC, merged